language: cpp

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo apt-get update;
  sudo apt-get install -y libgsl0-dev;
  sudo apt-get install libcppunit-dev;
  fi
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
