language: cpp

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libgsl0-dev libcppunit-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gsl cppunit; fi
  
before_script:
  - mkdir build
  - cd build
  - CXXFLAGS="-w" cmake ..

script: make -j8
